# Create a simple dataframe 
  
# importing pandas as pd 
import pandas as pd 
import argparse, sys, textwrap

parser=argparse.ArgumentParser()
parser.add_argument('--PicrustStratContribFilename', help = 'stratified picrust2 output, e.g *abun_contrib.tsv')
parser.add_argument('--Qiime2TaxonomyForASVs', help = 'The taxonomy file generated by Qiime2 indicating the multi-level taxonomy for each ASV ID')
parser.add_argument('--outfilename', help = 'Output filename to store stratified output')
parser.add_argument('--mapMetaCycID2names', help = 'OPTIONAL: Boolean <Y|N> to map metacyc pathway Ids to pathway names')
parser.add_argument('--MetaCycMapfile', help = 'A mapping file specifying the pathway names for Metacyc pathway IDs: For example, you can obtain one from the Metacyc workbench at https://metacyc.org/groups?tab=PUBLIC&orgid=META')

def main():
    # creating a dataframe
    args = parser.parse_args()
    StratfileN = args.PicrustStratContribFilename
    taxFileN = args.Qiime2TaxonomyForASVs
    outputfileN = args.outfilename
    
    pwayID_map_flag = args.mapMetaCycID2names
    pway_mapfile = args.MetaCycMapfile
 
    df = pd.read_csv(StratfileN, sep = '\t')
    print (df.head())
    
    Q2TaxDict = return_tax_dict(taxFileN)
    first10pairs = {k: Q2TaxDict[k] for k in list(Q2TaxDict)[100:120]}
    print("resultant dictionary : \n", first10pairs)
    
    df['taxonomy'] = df['taxon'].map(Q2TaxDict)
    print (df.head())
    df2 = df.filter(['sample','taxonomy','function','norm_taxon_function_contrib'], axis=1)
    print (df2.head())
    df2 = df2.rename(columns={"sample": "Sample", "taxonomy": "Genus", "function": "Gene", "norm_taxon_function_contrib": "Contribution"})
    print (df2.head())

    if (pwayID_map_flag == "Y" and pway_mapfile != ""):
        pwayID_nameMapDict = return_pwayIDNameMap(pway_mapfile)
        df2['pathwayName'] = df2['Gene'].map(pwayID_nameMapDict)
        df2.drop(labels=['Gene'], axis=1, inplace=True)
        df2.rename(columns={'pathwayName' :'Gene'},inplace=True)
        df2 = df2[['Sample','Genus','Gene','Contribution']]
        pd.DataFrame.to_csv(df2, path_or_buf=outputfileN, sep='\t', na_rep='', header=True, index=False, mode='w', line_terminator='\n', escapechar=None, decimal='.')
    else:
        print ("map flag not specified and mapping file not provided: skipping mapping")
        pd.DataFrame.to_csv(df2, path_or_buf=outputfileN, sep='\t', na_rep='', header=True, index=False, mode='w', line_terminator='\n', escapechar=None, decimal='.')


def return_tax_dict(taxfile):
    d = {}
    with open(taxfile) as f:
        for line in f:
            (key, val) = line.rstrip("\n").split("\t")
            d[str(key)] = val

    #print (d) 

    return d

def return_pwayIDNameMap(pwayMapF):
    d = {}
    with open(pwayMapF) as f:
        for line in f:
            fields = line.split(",")
            key = fields[0]
            val = fields[1] 
            d[str(key)] = str(val)
            #d[key].append(val)
    
    return d

if __name__ == "__main__":
        main();
